var annotated_dup =
[
    [ "Ipopt", "namespaceIpopt.html", "namespaceIpopt" ],
    [ "org", "namespaceorg.html", "namespaceorg" ],
    [ "CallbackFunctions", "classCallbackFunctions.html", "classCallbackFunctions" ],
    [ "HS071_NLP", "classHS071__NLP.html", "classHS071__NLP" ],
    [ "IpoptOptions", "classIpoptOptions.html", "classIpoptOptions" ],
    [ "IpoptRJournal", "classIpoptRJournal.html", "classIpoptRJournal" ],
    [ "IpoptRNLP", "classIpoptRNLP.html", "classIpoptRNLP" ],
    [ "Iterate", "classIterate.html", "classIterate" ],
    [ "LuksanVlcek1", "classLuksanVlcek1.html", "classLuksanVlcek1" ],
    [ "LuksanVlcek2", "classLuksanVlcek2.html", "classLuksanVlcek2" ],
    [ "LuksanVlcek3", "classLuksanVlcek3.html", "classLuksanVlcek3" ],
    [ "LuksanVlcek4", "classLuksanVlcek4.html", "classLuksanVlcek4" ],
    [ "LuksanVlcek5", "classLuksanVlcek5.html", "classLuksanVlcek5" ],
    [ "LuksanVlcek6", "classLuksanVlcek6.html", "classLuksanVlcek6" ],
    [ "LuksanVlcek7", "classLuksanVlcek7.html", "classLuksanVlcek7" ],
    [ "ma77_control_d", "structma77__control__d.html", "structma77__control__d" ],
    [ "ma77_info_d", "structma77__info__d.html", "structma77__info__d" ],
    [ "ma86_control_d", "structma86__control__d.html", "structma86__control__d" ],
    [ "ma86_info_d", "structma86__info__d.html", "structma86__info__d" ],
    [ "ma97_control_d", "structma97__control__d.html", "structma97__control__d" ],
    [ "ma97_info", "structma97__info.html", "structma97__info" ],
    [ "MatlabException", "classMatlabException.html", "classMatlabException" ],
    [ "MatlabFunctionHandle", "classMatlabFunctionHandle.html", "classMatlabFunctionHandle" ],
    [ "MatlabInfo", "classMatlabInfo.html", "classMatlabInfo" ],
    [ "MatlabProgram", "classMatlabProgram.html", "classMatlabProgram" ],
    [ "mc68_control", "structmc68__control.html", "structmc68__control" ],
    [ "mc68_info", "structmc68__info.html", "structmc68__info" ],
    [ "MittelmannBndryCntrlDiri1", "classMittelmannBndryCntrlDiri1.html", "classMittelmannBndryCntrlDiri1" ],
    [ "MittelmannBndryCntrlDiri2", "classMittelmannBndryCntrlDiri2.html", "classMittelmannBndryCntrlDiri2" ],
    [ "MittelmannBndryCntrlDiri3", "classMittelmannBndryCntrlDiri3.html", "classMittelmannBndryCntrlDiri3" ],
    [ "MittelmannBndryCntrlDiri3D", "classMittelmannBndryCntrlDiri3D.html", "classMittelmannBndryCntrlDiri3D" ],
    [ "MittelmannBndryCntrlDiri3D_27", "classMittelmannBndryCntrlDiri3D__27.html", "classMittelmannBndryCntrlDiri3D__27" ],
    [ "MittelmannBndryCntrlDiri3D_27BT", "classMittelmannBndryCntrlDiri3D__27BT.html", "classMittelmannBndryCntrlDiri3D__27BT" ],
    [ "MittelmannBndryCntrlDiri3Dsin", "classMittelmannBndryCntrlDiri3Dsin.html", "classMittelmannBndryCntrlDiri3Dsin" ],
    [ "MittelmannBndryCntrlDiri4", "classMittelmannBndryCntrlDiri4.html", "classMittelmannBndryCntrlDiri4" ],
    [ "MittelmannBndryCntrlDiriBase", "classMittelmannBndryCntrlDiriBase.html", "classMittelmannBndryCntrlDiriBase" ],
    [ "MittelmannBndryCntrlDiriBase3D", "classMittelmannBndryCntrlDiriBase3D.html", "classMittelmannBndryCntrlDiriBase3D" ],
    [ "MittelmannBndryCntrlDiriBase3D_27", "classMittelmannBndryCntrlDiriBase3D__27.html", "classMittelmannBndryCntrlDiriBase3D__27" ],
    [ "MittelmannBndryCntrlDiriBase3Dsin", "classMittelmannBndryCntrlDiriBase3Dsin.html", "classMittelmannBndryCntrlDiriBase3Dsin" ],
    [ "MittelmannBndryCntrlNeum1", "classMittelmannBndryCntrlNeum1.html", "classMittelmannBndryCntrlNeum1" ],
    [ "MittelmannBndryCntrlNeum2", "classMittelmannBndryCntrlNeum2.html", "classMittelmannBndryCntrlNeum2" ],
    [ "MittelmannBndryCntrlNeum3", "classMittelmannBndryCntrlNeum3.html", "classMittelmannBndryCntrlNeum3" ],
    [ "MittelmannBndryCntrlNeum4", "classMittelmannBndryCntrlNeum4.html", "classMittelmannBndryCntrlNeum4" ],
    [ "MittelmannBndryCntrlNeumBase", "classMittelmannBndryCntrlNeumBase.html", "classMittelmannBndryCntrlNeumBase" ],
    [ "MittelmannDistCntrlDiri1", "classMittelmannDistCntrlDiri1.html", "classMittelmannDistCntrlDiri1" ],
    [ "MittelmannDistCntrlDiri2", "classMittelmannDistCntrlDiri2.html", "classMittelmannDistCntrlDiri2" ],
    [ "MittelmannDistCntrlDiri3", "classMittelmannDistCntrlDiri3.html", "classMittelmannDistCntrlDiri3" ],
    [ "MittelmannDistCntrlDiri3a", "classMittelmannDistCntrlDiri3a.html", "classMittelmannDistCntrlDiri3a" ],
    [ "MittelmannDistCntrlDiriBase", "classMittelmannDistCntrlDiriBase.html", "classMittelmannDistCntrlDiriBase" ],
    [ "MittelmannDistCntrlNeumA1", "classMittelmannDistCntrlNeumA1.html", "classMittelmannDistCntrlNeumA1" ],
    [ "MittelmannDistCntrlNeumA2", "classMittelmannDistCntrlNeumA2.html", "classMittelmannDistCntrlNeumA2" ],
    [ "MittelmannDistCntrlNeumA3", "classMittelmannDistCntrlNeumA3.html", "classMittelmannDistCntrlNeumA3" ],
    [ "MittelmannDistCntrlNeumABase", "classMittelmannDistCntrlNeumABase.html", "classMittelmannDistCntrlNeumABase" ],
    [ "MittelmannDistCntrlNeumB1", "classMittelmannDistCntrlNeumB1.html", "classMittelmannDistCntrlNeumB1" ],
    [ "MittelmannDistCntrlNeumB2", "classMittelmannDistCntrlNeumB2.html", "classMittelmannDistCntrlNeumB2" ],
    [ "MittelmannDistCntrlNeumB3", "classMittelmannDistCntrlNeumB3.html", "classMittelmannDistCntrlNeumB3" ],
    [ "MittelmannDistCntrlNeumBBase", "classMittelmannDistCntrlNeumBBase.html", "classMittelmannDistCntrlNeumBBase" ],
    [ "MittelmannParaCntrl5_1", "classMittelmannParaCntrl5__1.html", [
      [ "ProblemSpecs", "classMittelmannParaCntrl5__1_1_1ProblemSpecs.html", "classMittelmannParaCntrl5__1_1_1ProblemSpecs" ]
    ] ],
    [ "MittelmannParaCntrl5_2_1", "classMittelmannParaCntrl5__2__1.html", [
      [ "ProblemSpecs", "classMittelmannParaCntrl5__2__1_1_1ProblemSpecs.html", "classMittelmannParaCntrl5__2__1_1_1ProblemSpecs" ]
    ] ],
    [ "MittelmannParaCntrl5_2_2", "classMittelmannParaCntrl5__2__2.html", [
      [ "ProblemSpecs", "classMittelmannParaCntrl5__2__2_1_1ProblemSpecs.html", "classMittelmannParaCntrl5__2__2_1_1ProblemSpecs" ]
    ] ],
    [ "MittelmannParaCntrl5_2_3", "classMittelmannParaCntrl5__2__3.html", [
      [ "ProblemSpecs", "classMittelmannParaCntrl5__2__3_1_1ProblemSpecs.html", "classMittelmannParaCntrl5__2__3_1_1ProblemSpecs" ]
    ] ],
    [ "MittelmannParaCntrl5_try", "classMittelmannParaCntrl5__try.html", [
      [ "ProblemSpecs", "classMittelmannParaCntrl5__try_1_1ProblemSpecs.html", "classMittelmannParaCntrl5__try_1_1ProblemSpecs" ]
    ] ],
    [ "MittelmannParaCntrlBase", "classMittelmannParaCntrlBase.html", "classMittelmannParaCntrlBase" ],
    [ "MyNLP", "classMyNLP.html", "classMyNLP" ],
    [ "Options", "classOptions.html", "classOptions" ],
    [ "RegisteredTNLP", "classRegisteredTNLP.html", "classRegisteredTNLP" ],
    [ "RegisteredTNLPs", "classRegisteredTNLPs.html", "classRegisteredTNLPs" ],
    [ "SparseMatrix", "classSparseMatrix.html", "classSparseMatrix" ],
    [ "TutorialCpp_NLP", "classTutorialCpp__NLP.html", "classTutorialCpp__NLP" ]
];