/* IPOPT/include/config.h.  Generated by configure.  */
/* IPOPT/include/config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to dummy `main' function (if any) required to link to the Fortran
   libraries. */
/* #undef F77_DUMMY_MAIN */

/* Define to a macro mangling the given C identifier (in lower and upper
   case), which must not contain underscores, for linking with Fortran. */
#define F77_FUNC(name,NAME) NAME

/* As F77_FUNC, but for C identifiers containing underscores. */
#define F77_FUNC_(name,NAME) NAME

/* Define if F77 and FC dummy `main' functions are identical. */
/* #undef FC_DUMMY_MAIN_EQ_F77 */

/* Define to 1 if CPU_TIME can be use to measure CPU time */
/* #undef HAVE_CPU_TIME */

/* Define to 1 if ETIME can be use to measure CPU time */
#define HAVE_ETIME 

/* Define to 1 if you have the <float.h> header file. */
#define HAVE_FLOAT_H 1

/* Define to 1 if you have the <ieeefp.h> header file. */
/* #undef HAVE_IEEEFP_H */

/* Define to 1 if you have the <inttypes.h> header file. */
/* #undef HAVE_INTTYPES_H */

/* Define to 1 if MA27 is available */
#define HAVE_MA27 1

/* Define to 1 if MA28 is available */
/* #undef HAVE_MA28 1 */

/* Define to 1 if MA47 is available */
/* #undef HAVE_MA47 */

/* Define to 1 if MA48 is available */
/* #undef HAVE_MA48 */

/* Define to 1 if MA57 is available */
/* #undef HAVE_MA57 */

/* Define to 1 if you have the <math.h> header file. */
#define HAVE_MATH_H 1

/* Define to 1 if MC19 is available */
#define HAVE_MC19 1

/* Define to 1 if MC29 is available */
/* #undef HAVE_MC29 */

/* Define to 1 if MC30 is available */
/* #undef HAVE_MC30 */

/* Define to 1 if MC35 is available */
/* #undef HAVE_MC35 */

/* Define to 1 if MC39 is available */
/* #undef HAVE_MC39 */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if TRON is available */
/* #undef HAVE_TRON */

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */

/* Define to 1 if you want to compile the AMPL executable with support for
   MPECs */
/* #undef INCLUDE_CC */

/* Define to the C type corresponding to Fortran INTEGER */
#define INTEGER_TYPE long

/* Define to be the name of C-function for NaNInf check */
#define MY_C_FINITE _finite

/* Define to 1 if MA27 is given in the old, non-threadsafe version */
/* #undef OLD_MA27 */

/* Name of package */
#define PACKAGE "ipopt"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "coin-ipopt@www-124.ibm.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "ipopt"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "ipopt 2.2.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "ipopt"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.2.0"

/* The size of a `double', as computed by sizeof. */
#define SIZEOF_DOUBLE 8

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `int *', as computed by sizeof. */
#define SIZEOF_INT_P 4

/* Define to 1 if pointers consists of 4 bytes */
#define SIZEOF_INT_P_IS_4 1

/* Define to 1 if pointers consists of 8 bytes */
/* #undef SIZEOF_INT_P_IS_8 */

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if Fortran compiler understand %VAL and malloc should be used
   */
#define USE_MALLOC 1

/* Version number of package */
#define VERSION "2.2.0"

/* Define to 1 if on AIX 3.
   System headers sometimes define this.
   We just want to avoid a redefinition error message.  */
#ifndef _ALL_SOURCE
/* # undef _ALL_SOURCE */
#endif

/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif

/* Define to 1 if on MINIX. */
/* #undef _MINIX */

/* Define to 2 if the system does not provide POSIX.1 features except with
   this defined. */
/* #undef _POSIX_1_SOURCE */

/* Define to 1 if you need to in order for `stat' and other things to work. */
/* #undef _POSIX_SOURCE */
